---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: projects.registry.vmware.com/nsxt_gen_pipeline/nsx-t-gen-worker
    tag: py3

inputs:
  - name: nsx-t-gen-pipeline
  - name: nsxt-ansible

run:
  path: nsx-t-gen-pipeline/tasks/add-nsx-t-routers/task.sh
