---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: projects.registry.vmware.com/nsxt_gen_pipeline/nsx-t-gen-worker
    tag: ubuntu18-v1

inputs:
  - name: nsx-t-gen-pipeline
  - name: nsxt-ansible
  - name: ovftool

run:
  path: nsx-t-gen-pipeline/tasks/install-nsx-t/task.sh
